### ISSUE TITLE
Hangs when mounting NFS shared folders

### ISSUE THREAD

**Issue by herb-o** [wckr/wocker#10] opened 2015-03-21 04:32 UTC
I am running ubuntu 14.04 & have installed
         sudo apt-get install nfs-kernel-server

But when running 'vagrant up' it hangs at
         nfsd running
         exportfs: /path_to../wocker/data does not support NFS export
         ==> default: Mounting NFS shared folders...

Is there a way around this?

**Comment by ixkaito** [comment] 2015-04-01 11:36
Wocker uses CoreOS on Vagrant. Are you able to start up the official CoreOS on Vagrant?

```
$ git clone https://github.com/coreos/coreos-vagrant.git && cd coreos-vagrant
```

```
$ vagrant up
```

Please try if this finishes without error, and you can `$ vagrant ssh` after it.
For more information, please see https://coreos.com/docs/running-coreos/platforms/vagrant/.

**Comment by herb-o** [comment] 2015-04-07 08:30
I was able to run coreos-vagrant. Also got the original image up & running [the wocker commands working ] after I commented out
<code>config.vm.synced_folder "./data", "/home/core/data", create: true, id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']</code>
in the Vagrantfile.
I was then able to <code>vagrant ssh</code> into both

Then I applied the comments config.vm.synced_folder to both images, & then ran. <code>vagrant up</code> I still got
<code>...does not support NFS export</code>

Re-checked had installed  <code>sudo apt-get install nfs-common nfs-kernel-server</code>

**Comment by alessandro-aglietti** [comment] 2015-04-15 10:45
Same for me on OSX 10.10.3.

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'nolock,vers=3,udp' 172.17.8.1:'/Users/accountname/Downloads/bitbucket/wocker/data' /home/core/data

Stdout from the command:



Stderr from the command:

mount.nfs: Connection timed out
```

I was able to run coreos-vagrant without problems.

I tried the @not-herbo workaround but I get and error during docker pull I think.

```
==> default: Pulling fs layer
==> default: 4da25f3ec4b6: Download complete
==> default: 895597c93904: Pulling metadata
==> default: 895597c93904: Pulling fs layer
==> default: 895597c93904: Download complete
==> default: 57a62e094eda: Pulling metadata
==> default: 57a62e094eda: Pulling fs layer
==> default: 57a62e094eda: Download complete
==> default: 57a62e094eda: Download complete
==> default: Status: Downloaded newer image for wocker/wocker:latest
==> default: 61c467844cd4a46cd716f9770d85cf492d0fea3764eac85491297ab35e210740
==> default: time="2015-04-15T10:39:26Z" level="fatal" msg="mkdir /home/core/data/61c467844cd4: permission denied" 
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

After a vagrant destroy, the vm start but without the NFS sync.

**Comment by alessandro-aglietti** [comment] 2015-04-15 12:10
Gotchaaaa :)

In my case the PF firewall block incoming NFS connection ghgh

http://serverfault.com/questions/377170/which-ports-do-i-need-to-open-in-the-firewall-to-use-nfs

Open ports 111 (TCP and UDP) and 2049 (TCP and UDP) for the NFS server and it's work out-of-the-box.

great!

**Comment by ixkaito** [comment] 2015-04-22 18:53
@alessandro-aglietti 
Thank you for the information.

@not-herbo 
Does this help you?

**Comment by herb-o** [comment] 2015-04-27 09:03
I have tried with open ports 111 (TCP and UDP) and 2049 (TCP and UDP) but with no luck.
It is probably the host computer configuration.

**Comment by ixkaito** [comment] 2015-05-12 03:30
I have no idea why you was able to run coreos-vagrant but can't run Wocker. They have same settings of synced folder.

**Comment by unfulvio** [comment] 2015-05-13 20:09
does NFS works in Windows too? http://wptavern.com/wocker-create-a-docker-based-wordpress-development-environment-in-3-seconds#comment-65491

**Comment by unfulvio** [comment] 2015-05-13 21:26
I think I figured out that the problem is NFS - so I changed this line like so:

```
config.vm.synced_folder "./data", "/home/core/data", create: true, id: "core"
```

switching to VBoxSf doesn't fix the problem because it requires guest additions

```
vb.check_guest_additions = true
vb.functional_vboxsf  = true
```

but virtual box additions are not available in CoreOS: 
http://comments.gmane.org/gmane.linux.coreos.devel/168

http://stackoverflow.com/questions/22344328/vagrant-coreos-image-drops-shared-folders-in-virtualbox-4-3-2-in-os-x-on-reboot

I'm still working on it to see if there's a solution

**Comment by alessandro-aglietti** [comment] 2015-05-13 21:53
RTMF

http://docs.vagrantup.com/v2/synced-folders/nfs.html

_Windows *_users*_:_ NFS folders do not work on Windows hosts. Vagrant will
ignore your request for NFS synced folders on Windows.
Il 13/mag/2015 22:09, "Fulvio Notarstefano" notifications@github.com ha
scritto:

**Comment by unfulvio** [comment] 2015-05-13 23:40
read above, I was trying to switch to vboxsf, but then there's another problem with CoreOS, I'm experimenting with other boxes based on Ubuntu or Rancheros (this repo seem to have took inspiration from Rancher?) but I understand that following that route will make any solution out of scope here

**Comment by ixkaito** [comment] 2015-05-14 05:43
It seems you need a Vagrant plugin `vagrant-winnfsd` to support NFS on Windows.

Could you please install it then try again.

```
$ vagrant plugin install vagrant-winnfsd
```

If this works, I will add it to the documentation.

**Comment by ixkaito** [comment] 2015-05-14 06:01
You will also need to declare some sort of network in order for NFS to work.
A private dhcp network is required for NFS to work (on Windows hosts, at least).
Please change the line 49 in the Vagrantfile to:

``` ruby
config.vm.network :private_network, ip: "172.17.8.23", type: "dhcp"
```

See: https://github.com/GM-Alex/vagrant-winnfsd

**Comment by ixkaito** [comment] 2016-01-04 22:53
Wocker 1.0.0 is now available. http://wckr.github.io/
Please have a try on Windows. You may have to launch the shell application as an admin to run Wocker.

**Closed as completed** 2016-01-26 07:29 UTC
Labels: help wanted
